basePath: /gin/api/v1
definitions:
  models.Hi:
    properties:
      msg:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /gin/api/v1/hi:
    get:
      consumes:
      - application/json
      description: Health check.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Hi'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Health check.
      tags:
      - Hi
swagger: "2.0"
